// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v01/acc/profile": {
            "get": {
                "description": "유저 프로필 정보를 가져는 함수다. 다음과 같은 정보를 가져온다. [닉네임, 나의 여행계획 카운트, 나의 Dynamic NFT 카운트, 좋아요 카운트 , 댓글 카운트]",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserProfileHandler(나의 프로필 정보 가져오기)"
                ],
                "summary": "계정주소, 닉네임을 입력합니다.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "walletAccount",
                        "name": "walletAccount",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "nickName",
                        "name": "nickName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v01/acc/register": {
            "post": {
                "description": "유저 닉네임을 등록 및 수정 해주는 함수로 지갑계정으로 연결 후 사용자가 닉네임을 입력할 수 있다. 이후 닉네임 수정은 자유롭게 가능하다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserRegisterHandler(닉네임 등록/수정)"
                ],
                "summary": "계정주소, 닉네임을 입력합니다.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "walletAccount",
                        "name": "walletAccount",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "nickName",
                        "name": "nickName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v01/badge/user": {
            "get": {
                "description": "사용자 위치를 참고해서 뱃지를 발급하는 함수",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GetMyBadge(나의 뱃지 가져오기)"
                ],
                "summary": "내가 발급한 뱃지를 가져오는 함수",
                "parameters": [
                    {
                        "type": "string",
                        "description": "walletAccount",
                        "name": "walletAccount",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v01/trip/allplan": {
            "get": {
                "description": "모든 여행계획을  MongoDB에서 가져오는 함수. 아무 파라미터가 없다 전체를 조회한다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GetAllTrip(전체 여행계획 가져오기)"
                ],
                "summary": "모든 여행계획을 가져오는 함수",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v01/trip/myplan": {
            "get": {
                "description": "나의 여행계획을 MongoDB에서 가져오는 함수, 계정주소로 파악한 후 가져온다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GetMyTrip(나의 여행계획 가져오기)"
                ],
                "summary": "나의 여행계획을 가져오는 함수",
                "parameters": [
                    {
                        "type": "string",
                        "description": "walletAccount",
                        "name": "walletAccount",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v01/trip/search": {
            "get": {
                "description": "여행계획의 제목 중 일치하는 문자열에 대해 콘텐츠를 리스폰스해주는 검색 API, 단어 단위로 구현, 예를 들어 Paris로 무작정이라고 하면 \"Paris로\" 까지 입력해야된다. q=\"Paris로\" 이런식으로 입력하면 된다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SearchTrip(여행계획 단어단위 검색하기)"
                ],
                "summary": "여행계획을 검색하는 API",
                "parameters": [
                    {
                        "type": "string",
                        "description": "q",
                        "name": "q",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
