info:
  contact: {}
paths:
  /v01/acc/nickname:
    post:
      consumes:
      - application/json
      description: 유저 프로필 업데이트하는 함수
      parameters:
      - description: walletAccount
        in: path
        name: walletAccount
        required: true
        type: string
      - description: nickName
        in: path
        name: nickName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 계정주소, 닉네임을 입력합니다.
      tags:
      - UserEditHandler
  /v01/acc/profile:
    get:
      consumes:
      - application/json
      description: 유저 프로필 정보를 가져는 함수
      parameters:
      - description: walletAccount
        in: path
        name: walletAccount
        required: true
        type: string
      - description: nickName
        in: path
        name: nickName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 계정주소, 닉네임을 입력합니다.
      tags:
      - UserProfileHandler
  /v01/acc/register:
    post:
      consumes:
      - application/json
      description: 유저를 등록해주는 함수
      parameters:
      - description: walletAccount
        in: path
        name: walletAccount
        required: true
        type: string
      - description: nickName
        in: path
        name: nickName
        required: true
        type: string
      - description: password
        in: path
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 계정주소, 닉네임, 비밀번호를 입력합니다.
      tags:
      - UserRegisterHandler
  /v01/badge/issue:
    post:
      consumes:
      - application/json
      description: 사용자 위치를 참고해서 뱃지를 발급하는 함수
      parameters:
      - description: walletAccount
        in: path
        name: walletAccount
        required: true
        type: string
      - description: latitude
        in: path
        name: latitude
        required: true
        type: string
      - description: longitude
        in: path
        name: longitude
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 위도, 경도를 입력받고 해당하는 나라의 리소스를 참고해서 뱃지를 발급해줍니다.
      tags:
      - CreateBadge
  /v01/badge/user:
    get:
      consumes:
      - application/json
      description: 사용자 위치를 참고해서 뱃지를 발급하는 함수
      parameters:
      - description: walletAccount
        in: path
        name: walletAccount
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 나의 뱃지를 가져오는 함수
      tags:
      - GetMyBadge
swagger: "2.0"
