definitions:
  model.Account:
    properties:
      accountId:
        description: 계정 ID
        type: integer
      commentCount:
        description: 댓글 카운트
        type: integer
      likeCount:
        description: 좋아요 카운트
        type: integer
      myDnftCount:
        description: DNFT뱃지 카운트
        type: integer
      myTripCount:
        description: 여행계획 카운트
        type: integer
      nickName:
        description: 닉네임
        type: string
      walletAccount:
        description: 지갑 계정 주소
        type: string
    type: object
  model.DayItem:
    properties:
      endDate:
        description: "세부 여행 종료날짜 \t/예시  : 15:15:00"
        type: string
      note:
        description: 세부 여행 메모
        type: string
      startDate:
        description: "세부 여행 시작시간 \t/예시  : 09:15:00"
        type: string
      title:
        description: 세부 여행 타이틀
        type: string
    type: object
  model.EncyclopediaDNFT:
    properties:
      dnftCountry:
        description: 국가
        type: string
      dnftId:
        description: 전체 dnftID
        type: integer
      dnftImgUrl:
        description: 이미지URL로 쓸 변수
        type: string
      dnftTier:
        description: 티어
        type: string
      dnftTime:
        description: 발급 시간
        type: string
      issueCount:
        description: 계정별, 국가별 발급횟수를 체크하는 변수
        type: integer
      latitude:
        description: 위도
        type: number
      longitude:
        description: 경도
        type: number
      walletAccount:
        description: 지갑계정
        type: string
    type: object
  model.TripPlan:
    properties:
      dayItems:
        description: days 아이템
        items:
          $ref: '#/definitions/model.DayItem'
        type: array
      nickName:
        description: 닉네임
        type: string
      tripArrival:
        description: 여행출발
        type: string
      tripCountry:
        description: 여행국가
        type: string
      tripDeparture:
        description: 여행도착
        type: string
      tripId:
        description: 여행계획 아이디
        type: integer
      tripTitle:
        description: 여행계획 제목
        type: string
      walletAccount:
        description: 지갑주소 계정
        type: string
    type: object
info:
  contact: {}
paths:
  /v01/acc/profile:
    get:
      consumes:
      - application/json
      description: 유저 프로필 정보를 가져는 함수다. 다음과 같은 정보를 가져온다. [닉네임, 나의 여행계획 카운트, 나의 Dynamic
        NFT 카운트, 좋아요 카운트 , 댓글 카운트]
      parameters:
      - description: walletAccount
        in: path
        name: walletAccount
        required: true
        type: string
      - description: nickName
        in: path
        name: nickName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Account'
            type: array
      summary: 계정주소를 입력합니다.
      tags:
      - UserProfileHandler(나의 프로필 정보 가져오기)
  /v01/acc/register:
    post:
      consumes:
      - application/json
      description: 유저 닉네임을 등록 및 수정 해주는 함수로 지갑계정으로 연결 후 사용자가 닉네임을 입력할 수 있다. 이후 닉네임
        수정은 자유롭게 가능하다.
      parameters:
      - description: walletAccount
        in: path
        name: walletAccount
        required: true
        type: string
      - description: nickName
        in: path
        name: nickName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Account'
            type: array
      summary: 계정주소, 닉네임을 입력합니다.
      tags:
      - UserRegisterHandler(닉네임 등록/수정)
  /v01/badge/issue:
    post:
      consumes:
      - application/json
      description: 위도, 경도를 입력받고 해당하는 나라의 리소스(ipfs uri, nft metadata)를 참고해서 뱃지를 발급해줍니다.
      parameters:
      - description: walletAccount
        in: path
        name: walletAccount
        required: true
        type: string
      - description: latitude
        in: path
        name: latitude
        required: true
        type: string
      - description: longitude
        in: path
        name: longitude
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.EncyclopediaDNFT'
            type: array
      summary: 지갑계정, 위도, 경도를 입력해줍니다.
      tags:
      - CreateBadge(뱃지 발급)
  /v01/badge/user:
    get:
      consumes:
      - application/json
      description: 사용자 위치를 참고해서 뱃지를 발급하는 함수
      parameters:
      - description: walletAccount
        in: path
        name: walletAccount
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.EncyclopediaDNFT'
            type: array
      summary: 지갑계정을 입력해줍니다.
      tags:
      - GetMyBadge(나의 뱃지 가져오기)
  /v01/trip/allplan:
    get:
      consumes:
      - application/json
      description: 모든 여행계획을  MongoDB에서 가져오는 함수. 아무 파라미터가 없다 전체를 조회한다.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.TripPlan'
            type: array
      summary: 모든 여행계획을 가져온다.
      tags:
      - GetAllTrip(전체 여행계획 가져오기)
  /v01/trip/delete/:num:
    delete:
      consumes:
      - application/json
      description: 트립아이디를 입력하면 해당하는 게시물을 삭제합니다.
      parameters:
      - description: tripId
        in: path
        name: tripId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.TripPlan'
            type: array
      summary: 트립아이디를 delete 뒤에 입력하면 해당하는 트립 아이디의 게시물이 삭제됩니다.
      tags:
      - DeleteTrip(나의 여행계획 중 디테일 페이지를 가져와줌)
  /v01/trip/detail/:num:
    get:
      consumes:
      - application/json
      description: 트립아이디를 입력하면 해당하는 상세페이지를 보여줍니다.
      parameters:
      - description: tripId
        in: path
        name: tripId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.TripPlan'
            type: array
      summary: 트립아이디를 detail 뒤에 입력하면 해당하는 트립 아이디가 출력됩니다.
      tags:
      - GetDetailTrip(나의 여행계획 중 디테일 페이지를 가져와줌)
  /v01/trip/myplan:
    get:
      consumes:
      - application/json
      description: 나의 여행계획을 MongoDB에서 가져오는 함수, 계정주소로 파악한 후 가져온다.
      parameters:
      - description: walletAccount
        in: path
        name: walletAccount
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.TripPlan'
            type: array
      summary: 지갑계정을 입력한다.
      tags:
      - GetMyTrip(나의 여행계획 가져오기)
    post:
      consumes:
      - application/json
      description: days에는 day1, day2단위로 아이템이 있고 각 day1별로 시간과 imtes가 있으며 각각 여행시작시간,
        종료시간, 이미지, 타이틀, 설명, 메모등을 입력할 수 있습니다.
      parameters:
      - description: walletAccount
        in: path
        name: walletAccount
        required: true
        type: string
      - description: tripTitle
        in: path
        name: tripTitle
        required: true
        type: string
      - description: tripCountry
        in: path
        name: tripCountry
        required: true
        type: string
      - description: tripDeparture
        in: path
        name: tripDeparture
        required: true
        type: string
      - description: tripArrival
        in: path
        name: tripArrival
        required: true
        type: string
      - description: days
        in: path
        name: days
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.TripPlan'
            type: array
      summary: 지갑계정, 제목, 나라, 출발날짜, 도착날짜 등을 입력합니다. days는 아이템을 담은 배열입니다.
      tags:
      - CreateTripPlan(나의 여행계획표 생성하기)
  /v01/trip/search:
    get:
      consumes:
      - application/json
      description: 여행계획의 제목 중 일치하는 문자열에 대해 콘텐츠를 리스폰스해주는 검색 API, 단어 단위로 구현, 예를 들어 Paris로
        무작정이라고 하면 "Paris로" 까지 입력해야된다. q="Paris로" 이런식으로 입력하면 된다.
      parameters:
      - description: q
        in: path
        name: q
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.TripPlan'
            type: array
      summary: q에 검색하고자 하는 키워드를 입력한다.
      tags:
      - SearchTrip(여행계획 단어단위 검색하기)
  /v01/trip/simpleplan:
    patch:
      consumes:
      - application/json
      description: days에는 day1, day2단위로 아이템이 있고 각 day1별로 시간과 imtes가 있으며 각각 여행시작시간,
        종료시간, 이미지, 타이틀, 설명, 메모등을 입력할 수 있습니다.
      parameters:
      - description: tripId
        in: path
        name: tripId
        required: true
        type: string
      - description: days
        in: path
        name: days
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.TripPlan'
            type: array
      summary: 지갑계정, 제목, 나라, 출발날짜, 도착날짜 등을 입력합니다. days를 입력으로 받는 함수 이후 데이터를 추가한다.
      tags:
      - CreateTripPlan(나의 여행계획표 생성하기)
    post:
      consumes:
      - application/json
      description: days에는 day1, day2단위로 아이템이 있고 각 day1별로 시간과 imtes가 있으며 각각 여행시작시간,
        종료시간, 이미지, 타이틀, 설명, 메모등을 입력할 수 있습니다.
      parameters:
      - description: walletAccount
        in: path
        name: walletAccount
        required: true
        type: string
      - description: triplTitle
        in: path
        name: triplTitle
        required: true
        type: string
      - description: tripCountry
        in: path
        name: tripCountry
        required: true
        type: string
      - description: tripDeparture
        in: path
        name: tripDeparture
        required: true
        type: string
      - description: tripArrival
        in: path
        name: tripArrival
        required: true
        type: string
      - description: days
        in: path
        name: days
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.TripPlan'
            type: array
      summary: 지갑계정, 제목, 나라, 출발날짜, 도착날짜 등을 입력합니다. days는 아이템을 담은 배열입니다.
      tags:
      - CreateTripPlan(나의 여행계획표 생성하기)
swagger: "2.0"
